version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python -m unittest discover -s tests -p "test_*.py"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - helloworld/core.py